version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: bombadle-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bombadle
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    profiles: ["dev"]
    container_name: bombadle-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 500
    restart: unless-stopped

volumes:
  postgres_data: