CREATE TABLE guess_list
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id BIGINT,
    guesses   JSONB,
    CONSTRAINT pk_guesslist PRIMARY KEY (id)
);

ALTER TABLE guess_list
    ADD CONSTRAINT uc_guesslist_player UNIQUE (player_id);

ALTER TABLE guess_list
    ADD CONSTRAINT FK_GUESSLIST_ON_PLAYER FOREIGN KEY (player_id) REFERENCES player (id);