ALTER TABLE player
    ADD COLUMN IF NOT EXISTS account_locked BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS admin_audit_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    actor_id BIGINT NOT NULL,
    change_type VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_admin_audit_log PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_audit_log_actor_id ON admin_audit_log (actor_id);

