ALTER TABLE player
    ADD COLUMN IF NOT EXISTS marked_for_deletion_at TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE IF NOT EXISTS deleted_account
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    original_player_id BIGINT NOT NULL,
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    total_guesses INTEGER NOT NULL,
    avatar_image VARCHAR(255) NOT NULL,
    auth_provider VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    deleted_by_actor_id BIGINT,
    CONSTRAINT pk_deleted_account PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_deleted_account_original_player_id ON deleted_account (original_player_id);

