CREATE TABLE IF NOT EXISTS admin_pending_change
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action_type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_admin_pending_change PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_pending_change_created_at ON admin_pending_change (created_at);

