CREATE
SEQUENCE IF NOT EXISTS character_card_seq START
WITH 1 INCREMENT BY 50;

CREATE
SEQUENCE IF NOT EXISTS player_seq START
WITH 1 INCREMENT BY 50;

CREATE
SEQUENCE IF NOT EXISTS quotes_seq START
WITH 1 INCREMENT BY 50;


CREATE TABLE character_affiliations
(
    character_id BIGINT       NOT NULL,
    affiliation  VARCHAR(255) NOT NULL
);

CREATE TABLE character_card
(
    id                       BIGINT       NOT NULL,
    name                     VARCHAR(255) NOT NULL,
    alive                    BOOLEAN,
    race                     VARCHAR(255),
    first_appearance_episode INTEGER,
    CONSTRAINT pk_character_card PRIMARY KEY (id)
);

CREATE TABLE player
(
    id                BIGINT       NOT NULL,
    login             VARCHAR(255) NOT NULL,
    email             VARCHAR(255) NOT NULL,
    role              VARCHAR(255) NOT NULL,
    password_hash     VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    last_login_at     TIMESTAMP WITHOUT TIME ZONE,
    today_score_id    BIGINT,
    avatar_image      VARCHAR(255),
    total_guesses     INTEGER,
    has_guessed_today BOOLEAN,
    CONSTRAINT pk_player PRIMARY KEY (id)
);

CREATE TABLE quotes
(
    id                BIGINT        NOT NULL,
    content           VARCHAR(1000) NOT NULL,
    character_card_id BIGINT        NOT NULL,
    CONSTRAINT pk_quotes PRIMARY KEY (id)
);

CREATE TABLE score
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    score_time_stamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    number_of_tries  INTEGER NOT NULL,
    CONSTRAINT pk_score PRIMARY KEY (id)
);

ALTER TABLE player
    ADD CONSTRAINT uc_player_email UNIQUE (email);

ALTER TABLE player
    ADD CONSTRAINT uc_player_login UNIQUE (login);

ALTER TABLE player
    ADD CONSTRAINT uc_player_today_score UNIQUE (today_score_id);

ALTER TABLE player
    ADD CONSTRAINT FK_PLAYER_ON_TODAY_SCORE FOREIGN KEY (today_score_id) REFERENCES score (id);

ALTER TABLE quotes
    ADD CONSTRAINT FK_QUOTES_ON_CHARACTER_CARD FOREIGN KEY (character_card_id) REFERENCES character_card (id);

ALTER TABLE character_affiliations
    ADD CONSTRAINT fk_character_affiliations_on_character_card FOREIGN KEY (character_id) REFERENCES character_card (id);