CREATE TABLE anonymous_guess_list
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guesses JSONB,
    CONSTRAINT pk_anonymousguesslist PRIMARY KEY (id)
);

CREATE TABLE anonymous_guess_session
(
    id                      UUID    NOT NULL,
    anonymous_guess_list_id BIGINT,
    is_guessed              BOOLEAN NOT NULL,
    score_timestamp         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_anonymousguesssession PRIMARY KEY (id)
);

ALTER TABLE anonymous_guess_session
    ADD CONSTRAINT uc_anonymousguesssession_anonymous_guess_list UNIQUE (anonymous_guess_list_id);

ALTER TABLE anonymous_guess_session
    ADD CONSTRAINT FK_ANONYMOUSGUESSSESSION_ON_ANONYMOUS_GUESS_LIST FOREIGN KEY (anonymous_guess_list_id) REFERENCES anonymous_guess_list (id);