CREATE TABLE activity_snapshot
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    timestamp              TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    logged_in_active_count INTEGER                                 NOT NULL,
    anonymous_active_count INTEGER                                 NOT NULL,
    CONSTRAINT pk_activity_snapshot PRIMARY KEY (id)
);