CREATE TABLE player_daily_statistic
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_id            BIGINT                                  NOT NULL,
    game_mode            VARCHAR(255)                            NOT NULL,
    puzzle_date          DATE                                    NOT NULL,
    solved_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    number_of_tries      INTEGER                                 NOT NULL,
    leaderboard_position INTEGER                                 NOT NULL,
    total_participants   INTEGER                                 NOT NULL,
    CONSTRAINT pk_player_daily_statistic PRIMARY KEY (id),
    CONSTRAINT uq_player_daily_statistic_player_mode_date UNIQUE (player_id, game_mode, puzzle_date),
    CONSTRAINT fk_player_daily_statistic_on_player FOREIGN KEY (player_id) REFERENCES player (id)
);

CREATE INDEX idx_player_daily_statistic_player_id ON player_daily_statistic (player_id);
