ALTER TABLE player ADD COLUMN current_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN longest_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN current_superstreak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE player ADD COLUMN longest_superstreak INTEGER NOT NULL DEFAULT 0;
