CREATE TABLE deleted_account_statistic
(
    id                             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted_account_id             BIGINT                                  NOT NULL,
    current_streak                 INTEGER                                 NOT NULL,
    longest_streak                 INTEGER                                 NOT NULL,
    current_superstreak            INTEGER                                 NOT NULL,
    longest_superstreak            INTEGER                                 NOT NULL,
    total_guesses                  INTEGER                                 NOT NULL,
    guesses_by_mode                JSONB,
    total_top3_finishes            INTEGER                                 NOT NULL,
    average_leaderboard_percentile DOUBLE PRECISION,
    captured_at                    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_deleted_account_statistic PRIMARY KEY (id)
);

CREATE INDEX idx_deleted_account_statistic_deleted_account_id ON deleted_account_statistic (deleted_account_id);
