CREATE TABLE daily_solver_statistic
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_mode               VARCHAR(255)                            NOT NULL,
    puzzle_date             DATE                                    NOT NULL,
    total_solvers           INTEGER                                 NOT NULL,
    total_anonymous_solvers INTEGER                                 NOT NULL,
    captured_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_daily_solver_statistic PRIMARY KEY (id),
    CONSTRAINT uq_daily_solver_statistic_mode_date UNIQUE (game_mode, puzzle_date)
);
