CREATE TABLE refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token_hash VARCHAR(64)                             NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE,
    revoked    BOOLEAN                                 NOT NULL,
    revoked_at TIMESTAMP WITHOUT TIME ZONE,
    user_id    BIGINT,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES player (id);