INSERT INTO character_card (id, name, gender, race, alive, first_appearance_episode) VALUES
                                                                                         (1, 'Kapitan Bomba', 'MALE', 'Czlowiek', TRUE, 1),
                                                                                         (2, 'Sebastian Bąk', 'MALE', 'Czlowiek', TRUE, 1),
                                                                                         (3, 'Janusz Sram', 'MALE', 'Czlowiek', TRUE, 1),
                                                                                         (4, 'Marik1234', 'MALE', NULL, TRUE, 87),
                                                                                         (5, 'Michal Glus', 'MALE', 'Kurvinox', TRUE, 56),
                                                                                         (6, 'Sułtan Kosmitow', 'MALE', 'Kurwczerw', TRUE, 55),
                                                                                         (7, 'JJ Torpeda', 'MALE', 'Czlowiek', TRUE, 34),
                                                                                         (8, 'Admirał Marycjusz Borubar', 'MALE', 'Czlowiek', FALSE, 1),
                                                                                         (9, 'Generał Lufa', 'MALE', 'Czlowiek', FALSE, 51),
                                                                                         (10, 'Michał Parchaś', 'MALE', 'Kurwczerw', FALSE, 121),
                                                                                         (11, 'Matka Sułtana Kosmitów', 'FEMALE', 'Kurwczerw', FALSE, 74),
                                                                                         (12, 'Admiral Ignacy Kuj', 'MALE', 'Czlowiek', TRUE, 131),
                                                                                         (13, 'Sztygar Mkbewe', 'MALE', 'Czlowiek', FALSE, 71),
                                                                                         (14, 'Modest Bomba', 'MALE', 'Czlowiek', TRUE, 114),
                                                                                         (15, 'Ojciec Pijo', 'MALE', 'Czlowiek', TRUE, 129);

INSERT INTO character_colors (character_id, colors) VALUES
                                                       (1, 'BIALY'),
                                                       (2, 'ZIELONY'),
                                                       (3, 'ZIELONY'),
                                                       (4, 'FIOLETOWY'),
                                                       (5, 'NIEBIESKI'),
                                                       (6, 'JASNOBRAZOWY'),
                                                       (7, 'ZOLTY'),
                                                       (8, 'BIALY'),
                                                       (9, 'ZIELONY'),
                                                       (10, 'JASNOBRAZOWY'),
                                                       (11, 'JASNOBRAZOWY'),
                                                       (12, 'BIALY'),
                                                       (13, 'CZERWONY'),
                                                       (14, 'POMARANCZOWY'),
                                                       (14, 'ZOLTY'),
                                                       (15, 'CZARNY'),
                                                       (15, 'NIEBIESKI');

INSERT INTO character_affiliations (character_id, affiliation) VALUES
                                                                   (1, 'Gwiezdna_Flota'), (1, 'Kapitan_Gwiezdnej_Floty'),
                                                                   (2, 'Gwiezdna_Flota'), (2, 'Szeregowy_Gwiezdnej_Floty'),
                                                                   (3, 'Gwiezdna_Flota'), (3, 'Szeregowy_Gwiezdnej_Floty'),
                                                                   (4, 'Kosmici'),
                                                                   (5, 'Gwiezdna_Flota'), (5, 'Kosmici'),
                                                                   (6, 'Sultanat_Kosmitow'),
                                                                   (7, 'Gwiezdna_Flota'), (7, 'Chorazy_Gwiezdnej_Floty'), (7, 'Kapitan_Gwiezdnej_Floty'), (7, 'Admiralowie_Gwiezdnej_Floty'),
                                                                   (8, 'Gwiezdna_Flota'), (8, 'Admiralowie_Gwiezdnej_Floty'),
                                                                   (9, 'Gwiezdna_Flota'),
                                                                   (10, 'Sultanat_Kosmitow'),
                                                                   (11, 'Sultanat_Kosmitow'),
                                                                   (12, 'Gwiezdna_Flota'), (12, 'Admiralowie_Gwiezdnej_Floty'),
                                                                   (13, 'Cywile'), (13, 'Sultanat_Kosmitow'),
                                                                   (14, 'Cywile'),
                                                                   (15, 'Cywile');