package com.bombadle.enums;

public enum AvatarImage {
    AVATAR_DEFAULT,
    AVATAR_BOMBA,
    AVATAR_GLUS,
    AVATAR_KURVINOX,
    AVATAR_LECINA,
    AVATAR_JANUSZ,
    AVATAR_SEBEK,
    AVATAR_TORPEDA,
    AVATAR_SKURWOL,
    AVATAR_CQURWOZAUR
}
